
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogMaven@1
  inputs:
    workingDirectory: '/school'
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'adopRt'
    targetResolveReleaseRepo: 'alpha-mvn-blr-libs-release'
    targetResolveSnapshotRepo: 'alpha-mvn-blr-libs-snapshot'
    artifactoryDeployService: 'adopRt'
    targetDeployReleaseRepo: 'alpha-mvn-blr-libs-release-local'
    targetDeploySnapshotRepo: 'alpha-mvn-blr-libs-snapshot'
    javaHomeOption: 'JDKVersion'
- task: JFrogBuildPromotion@1
  inputs:
    artifactoryConnection: 'adopRt'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    targetRepo: 'azuremvn-libs-release-local'
    status: 'Released'
    sourceRepo: 'azuremvn-libs-prod-local'
    includeDependencies: true
    copy: true
- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'adopxray'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true
    vuln: false